DATABASE_HOST = "mongodb://127.0.0.1:27017"
DATABASE_NAME = "macdMonitor"

ACCOUNT_COLLECTION = "Accounts"
ARCHIVED_UPDATES_COLLECTION = "ArchivedUpdates"
HOLDING_PROFILES_COLLECTION = "HoldingProfiles"
CRAIGSLIST_COLLECTION = "CraigslistRecords"

COLLECTIONS = [
    ACCOUNT_COLLECTION,
    ARCHIVED_UPDATES_COLLECTION,
    HOLDING_PROFILES_COLLECTION,
    CRAIGSLIST_COLLECTION,
]
